### ISSUE TITLE
pip install psycopg2 not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by jrunreal** [coopengo/tryton-training#2]
I was unable to install on Ubuntu 18.04
I first need to install "libpq-dev"

```
apt install libpq-dev
pip install psycopg2
```

Thanks for tutorial

**Comment by JCavallo** [comment]
Indeed, I updated the documentation.

You should also be able to use ``pip install psycopg2-binary`` which does not require dependencies AFAIK.
