### ISSUE TITLE
 How to use this repository is missing in Latest version (5.0)

### ISSUE THREAD

**Issue by jrunreal** [coopengo/tryton-training#3]
So, without this, this is hard to understand:
```
git checkout 5.0/step2
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

so do I have to clone first?:
`git clone https://github.com/coopengo/tryton-training.git`

And then using this foder for virtual env?
`virtualenv -p $(which python3) tryton-training`

Or should that be different directories?

Thanks

**Comment by JCavallo** [comment]
The "How to section" is common for all versions.

It says explicitely:

```markdown
When starting your training, you will need to:
- Install a tryton development environment
- Clone the training repository in it
- Create a database to work on
```

I've added another line about this in the 5.0 setup page.
