### ISSUE TITLE
Author genre is not existing befor homework 2 but assumed

### ISSUE THREAD

**Issue by jrunreal** [coopengo/tryton-training#4]
Hello
I was a little bit confuses, when I looked at the "5.0 step2 correction".
There is written: 
> You should have one more field on the **library.author** model. It should be wisely named editor, and be defined right before or after the existing genre field (since it is a data field).

But in https://github.com/coopengo/tryton-training/wiki/5.0-step2 I found nothing written about changing or adding something to class Author / 'library.author'.
We can also see this here: https://github.com/coopengo/tryton-training/blob/5.0/step2_completed/modules/library/library.py

May it should be **'library.book'** instead of **'library.author'**.

Even I was thinking we need to add 'books' field on 'library.author' :-)

Thanks for you work, I am very excited !

**Comment by JCavallo** [comment]
You're totally right, it was a typo.

I fixed this.
